Feature/sticky collection view
icapps/ios-delirium pull request #6
Opened 2016-11-30 12:46 UTC by doozMen

2016-11-30 13:50 UTC, fousa requested changes
I have some more remarks:

- Is it possible to align the style of the collectionView a bit more according to the current design of the example app's screens? 
![simulator screen shot 30 nov 2016 14 35 02](https://cloud.githubusercontent.com/assets/45648/20754649/3c3d4c84-b70c-11e6-992d-cd19f36025fc.png)

- I'm not a big fan of the bounce effect, it feels like I can completely break the collection view. 
![simulator screen shot 30 nov 2016 14 38 17](https://cloud.githubusercontent.com/assets/45648/20754644/371f5490-b70c-11e6-9d0b-550c2f493e28.png)

- The layout code needs some more inline comment, just for when we want to change something afterwards.

Nice addition though. 🚒

2016-11-30 13:50 UTC, fousa commented on Example/Example for Delirium/Modules/StickyCollectionViewLayout/StickyCell.swift
> +        super.layoutSubviews()
❓Is there a reason why you set the border's properties before the `super.layoutSubviews()` call?

2016-11-30 13:50 UTC, fousa commented on Example/Example for Delirium/Modules/StickyCollectionViewLayout/StickyCollectionViewController.swift
> +enum StickyCellIdentifier: String {
❓Seems like a bit of overkill for just one identifier, no?

2016-11-30 13:50 UTC, fousa commented on Example/Example for Delirium/Modules/StickyCollectionViewLayout/StickyCollectionViewController.swift
> +        let row1: [Column] = [.A, .B, .C, .D, .E, .F, .G, .H, .last]
I would move this to the viewModel instead of setting the data here. This is viewModel functionality.

2016-11-30 13:50 UTC, fousa commented on Example/Example for Delirium/Modules/StickyCollectionViewLayout/StickyCollectionViewController.swift
> +        guard let section = Row(rawValue: section) else {
Should be handled by the viewModel.

2016-11-30 13:50 UTC, fousa commented on Example/Example for Delirium/Modules/StickyCollectionViewLayout/StickyCollectionViewController.swift
> +        let row = Row(rawValue: indexPath.section)!
I would move all this logic to the `StickyCell` subclass.

2016-11-30 13:50 UTC, fousa commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +    public var preferredItemSize = CGSize(width: 150, height: 40)
I would prefer this not to be fixed. I think you can just request this from the `collectionViewLayout` property.

2016-11-30 13:50 UTC, fousa commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +            let filteredArray  = section.filter { rect.intersects($0.frame) }
I would add some comments here.

2016-11-30 13:50 UTC, fousa commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +                self.itemsSize.append(self.sizeForItemWithColumnIndex(index))
Why is the `itemSize` variable not multidimensional array like itemAttributes? Isn't this easier to work with when using sections?

2016-11-30 13:50 UTC, fousa commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +                    attributes.frame = frame
I think you can directly modify the `y` value like this `attributes.frame.origin.y = contentOffset.y`

2016-11-30 13:50 UTC, fousa commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +                    attributes.frame = frame
I think you can directly modify the `x` value like this `attributes.frame.origin.x = contentOffset.x`

2016-11-30 13:50 UTC, fousa commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +                    rowAttribute.frame = frame
I think you can directly modify the `y` value like this `attributes.frame.origin.y = contentOffset.y`

2016-11-30 13:50 UTC, fousa commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +                let itemSize = (self.itemsSize[index] as AnyObject).cgSizeValue
It would be nice to have some comments inside this function to explain what is happening here...

2016-11-30 13:50 UTC, fousa commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +                    rowAttribute.frame = frame
I think you can directly modify the `x` value like this `attributes.frame.origin.x = contentOffset.x`

2016-11-30 13:50 UTC, fousa commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +                xOffset += (itemSize?.width)!
The optional value is breakable... 💣

2016-12-02 16:44 UTC, doozMen commented
@fousa DANKU voor de goeie commentaar. Ik ga dit gebruiken in Brutex en update deze Branch daarmee. Ik zal je terug assignen als het klaar is. Maar nu heb ik al een aantal goeie tips om het beter te krijgen!

2016-12-04 13:39 UTC, fousa commented
You are welcome @doozMen'mans!! 🤘🏼

2016-12-16 11:42 UTC, doozMen commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +    public var preferredItemSize = CGSize(width: 150, height: 40)
Je kan dit doen met de uitleg die ik toegevoegd heb en veranderingen...

2016-12-16 11:47 UTC, doozMen commented on Sources/StickeyCollectionViewLayout/StickyCollectionViewLayout.swift
> +                    attributes.frame = frame
such nice detail

2017-02-15 11:24 UTC, closed without merging